version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/sdk/rust"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/frontend/web"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/frontend/desktop"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/frontend/browser-extension"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/sdk/typescript"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/plugins/vscode"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/mobile/android"
    schedule:
      interval: "weekly"
